on: [push]

name: CI for 'one-line-aeson-text' library

jobs:
  build:
    name: Test the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - '8.8.3'
          - '8.10.3'
          - '9.0.1'

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '.github/workflows/test.hs') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Test
        run: |
            cd one-line-aeson-text
            runhaskell --ghc-arg='-package process' ../.github/workflows/test.hs
        env:
          ghc: ${{ matrix.ghc }}
